### ISSUE TITLE
TODO: ENDPOINT

### ISSUE THREAD

**Issue by AkiaCode** [Helloyunho/discord.deno#1]
## AUDIT LOG
- [x] Get Guild Audit Log

## CHANNEL
- [x] Get Channel
- [x] Modify Channel
- [x] Delete/Close Channel
- [x] Get Channel Messages
- [x] Get Channel Message
- [x] Create Message
- [x] Channel CrossPost
- [x] Create Reaction
- [x] Delete Own Reaction 
- [x] Delete User Reaction
- [x] Get Reactions
- [x] Delete All Reactions
- [x] Delete All Reactions for Emoji
- [x] Edit Message
- [x] Delete Message
- [x] Bulk Delete Messages
- [x] Edit Channel Permissions
- [x] Get Channel Invites
- [x] Create Channel Invite
- [x] Delete Channel Permission
- [x] Follow News Channel
- [x] Trigger Typing Indicator
- [x] Get Pinned Messages
- [x] Add Pinned Channel Message
- [x] Delete Pinned Channel Message
- [x] Group DM Add Recipient

## EMOJI
- [x] List Guild Emojis
- [x] Get Guild Emoji
- [x] Create Guild Emoji
- [x] Modify Guild Emoji
- [x] Delete Guild Emoji

## GUILD
- [x] Create Guild
- [x] Get Guild
- [x] Get Guild Preview
- [x] Modify Guild
- [x] Delete Guild
- [x] Get Guild Channels
- [x] Create Guild Channel
- [x] Modify Guild Channel Positions
- [x] Get Guild Member
- [x] List Guild Members
- [x] Add Guild Member
- [x] Modify Guild Member
- [x] Modify Current User Nick
- [x] Add Guild Member Role
- [x] Remove Guild Member Role
- [x] Remove Guild Member
- [x] Get Guild Bans
- [x] Get Guild Ban
- [x] Create Guild Ban
- [x] Remove Guild Ban
- [x] Get Guild Roles
- [x] Create Guild Role
- [x] Modify Guild Role Positions
- [x] Modify Guild Role
- [x] Delete Guild Role
- [x] Get Guild Prune Count
- [x] Begin Guild Prune
- [x] Get Guild Voice Regions
- [x] Get Guild Invites
- [x] Get Guild Integrations
- [x] Create Guild Integration
- [x] Modify Guild Integration
- [x] Delete Guild Integration
- [x] Sync Guild Integration
- [x] Get Guild Widget Settings
- [x] Modify Guild Widget
- [x] Get Guild Widget
- [x] Get Guild Vanity URL
- [x] Get Guild Widget Image

## INVITE
- [x] Get Invite
- [x] Delete Invite

## TEMPLATE
- [x] Get Template
- [x] Create Guild from Template

## USER
- [x] Get Current User
- [x] Get User
- [x] Modify Current User
- [x] Get Current User Guilds
- [x] Leave Guild
- [x] Get User DMs
- [x] Create DM
- [x] Create Group DM
- [x] Get User Connections

## VOICE
- [x] List Voice Regions

## WEBHOOK
- [x] Create Webhook
- [x] Get Channel Webhooks
- [x] Get Guild Webhooks
- [x] Get Webhook
- [x] Get Webhook with Token
- [x] Modify Webhook
- [x] Modify Webhook with Token
- [x] Delete Webhook 
- [x] Delete Webhook with Token
- [x] Execute Webhook
- [x] Execute Slack-Compatible Webhook
- [x] Execute GitHub-Compatible Webhook

## CDN
- [x] Custom Emoji
- [x] Guild Icon
- [x] Guild Splash
- [x] Guild Discovery Splash
- [x] Guild Banner
- [x] Default User Avatar 
- [x] User Avatar
- [x] Application Icon
- [x] Application Asset
- [x] Achievement Icon
- [x] Team Icon

### GATEWAY
- [x] Get Gateway
- [x] Get Gateway Bot

**Comment by AkiaCode** [comment]
Done.
